# DO NOT CHANGE ANYTHING HERE, EVERYTHING WORKS !!!

# version: "2.1"

services:
  postgres:
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    ports:
      - "${HOST_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
    networks:
      - yapp-net

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - yapp-net

  migrate:
    image: migrate/migrate:latest
    restart: on-failure:5
    env_file:
      - ./.env
    volumes:
      - ./infra/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]

  yapp-server-1:
    build:
      context: .
      dockerfile: cmd/yapp-server/Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./:/app
    expose:
      - "${HTTP_PORT}"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: >
      sh -c "
        echo '‚è±  Waiting 10s for service to complete';
        sleep 10;
        echo 'üöÄ Starting Yapp server';
        air
      "
    networks:
      - yapp-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"

    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets:/app/assets:ro # static files haru server garna lai
      - nginx_logs:/var/log/nginx
    depends_on:
      - yapp-server-1
    networks:
      - yapp-net
    healthcheck:
      test: ["CMD-SHELL", "wget", "--quite", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  nginx_logs:

networks:
  yapp-net:
    driver: bridge
